# Generated by Django 4.2.3 on 2023-07-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vourcher_code',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
