# Generated by Django 4.2.3 on 2023-07-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orderitem_vourcher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bargainprice',
            name='vourcher_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
