# Generated by Django 4.2.3 on 2023-07-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
